name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  full-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install --no-bin-links

    - name: Fix mocha permissions
      run: chmod +x ./node_modules/.bin/mocha

    - name: Dependency check (npm audit)
      run: |
        npm audit --audit-level=moderate || echo "Audit completed with warnings"

    - name: Start app in background
      run: |
        npm start &
        sleep 3

    - name: Run integration tests
      run: npm test

    - name: Install Chrome & Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/


    - name: Run Selenium UI tests
      run: npm run ui-test
      env:
        CHROME_BIN: /usr/bin/google-chrome
